### ISSUE TITLE
Symfony 5 and PHP 8

### ISSUE THREAD

**Issue by Zul3s** [steevanb/doctrine-stats#15]
Hello and thank you for your work. 

Did you plan the Symfony 5 and PHP 8 compatibility ? 

Regards.

**Comment by steevanb** [comment]
Hi,

Yes i'm working on PHP8 compatibility, and some rework.

For now i think you can use it with Symfony 5, what is your problem?

**Comment by steevanb** [comment]
You can update to `2.0.0` to get it.
