### ISSUE TITLE
Strictly in development environment

### ISSUE THREAD

**Issue by HMAZonderland** [steevanb/doctrine-stats#2]
Nice library! Helped me a ton in my custom cms. I'm wondering if this would be strictly limited to a  development environment if I also wanted to include the hydration statistics. Since I'd have to update my composer file and include all these scripts.

**Comment by steevanb** [comment]
Hi, thanks !

You can add it in prod environment, but my advice is : don't do it.
It will slow Doctrine a little bit, add some dependencies, etc.
