### ISSUE TITLE
Hydration time

### ISSUE THREAD

**Issue by nurikabe** [steevanb/doctrine-stats#3]
*Love* this bundle, but having trouble getting hydration time to show.  I think I've got everything installed as per the README.  Any advice on how to debug?

**Comment by steevanb** [comment]
Could you send send me a screenshot of `Statistics` panel (exemple : http://localhost.dev/_profiler/XXXXX?panel=doctrine_stats) ? And your `extra` configuration in `composer.json` ?

**Comment by nurikabe** [comment]
Thanks @steevanb!  Here you go:

![image](https://cloud.githubusercontent.com/assets/83678/24259451/4ec1eaea-0fc7-11e7-8b2f-8e70d43fecec.png)

    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "symlink",
        "composer-overload-cache-dir": "var/cache",
        "composer-overload-class-dev": {
            "Doctrine\\ORM\\Internal\\Hydration\\ArrayHydrator": {
                "original-file": "vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ArrayHydrator.php",
                "overload-file": "vendor/steevanb/doctrine-stats/ComposerOverloadClass/Doctrine/ORM/Internal/ArrayHydrator.php"
            },
            "Doctrine\\ORM\\Internal\\Hydration\\ObjectHydrator": {
                "original-file": "vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php",
                "overload-file": "vendor/steevanb/doctrine-stats/ComposerOverloadClass/Doctrine/ORM/Internal/ObjectHydrator.php"
            },
            "Doctrine\\ORM\\Internal\\Hydration\\ScalarHydrator": {
                "original-file": "vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ScalarHydrator.php",
                "overload-file": "vendor/steevanb/doctrine-stats/ComposerOverloadClass/Doctrine/ORM/Internal/ScalarHydrator.php"
            },
            "Doctrine\\ORM\\Internal\\Hydration\\SimpleObjectHydrator": {
                "original-file": "vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php",
                "overload-file": "vendor/steevanb/doctrine-stats/ComposerOverloadClass/Doctrine/ORM/Internal/SimpleObjectHydrator.php"
            },
            "Doctrine\\ORM\\Internal\\Hydration\\SingleScalarHydrator": {
                "original-file": "vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SingleScalarHydrator.php",
                "overload-file": "vendor/steevanb/doctrine-stats/ComposerOverloadClass/Doctrine/ORM/Internal/SingleScalarHydrator.php"
            }
        },
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.8-dev"
        }
    }

**Comment by steevanb** [comment]
Looks fine :)
Same thing with `autoload` and `scripts` configs in your `composer.json` ?

**Comment by nurikabe** [comment]
Aha.. I just tried a reinstall and get this:

`Class steevanb\ComposerOverloadClass\OverloadClass is not autoloadable, can not call pre-autoload-dump script`

Here's my `autoload` config:

    "autoload": {
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ],
        "psr-4": {
            "": "src/",
            "ComposerOverloadClass\\": "var/cache/ComposerOverloadClass"
        }
    },

Should I move `ComposerOverloadClass` to `classmap` perhaps?

**Comment by steevanb** [comment]
Think your forgot to add this :
```
"require-dev": {
    "steevanb/composer-overload-class": "^1.1"
},
```

**Comment by nurikabe** [comment]
It works!  Thanks a ton :sunglasses:

**Comment by steevanb** [comment]
Nothing !

How did you find this repo ?

**Comment by nurikabe** [comment]
You know, I don't quite remember.  I originally installed it a few months ago.  I think I was searching for something like "doctrine hydration time" and it came up.

**Comment by steevanb** [comment]
Ok, thanks !
