### ISSUE TITLE
Exception division by 0

### ISSUE THREAD

**Issue by jewome62** [steevanb/doctrine-stats#4]
I have a query which don't have stats (queryTime and hydrationTime equals to 0)

![image](https://cloud.githubusercontent.com/assets/472429/24908729/6f971a3e-1ec1-11e7-996e-9838820101f6.png)

**Comment by steevanb** [comment]
Should be fixed in `1.2.1`
https://github.com/steevanb/doctrine-stats/commit/d958cd0e01135e02d688765bd7295d82dc83a4ff

Thanks !
